//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PomeDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public byte[] LastName { get; set; }
        public string GivenName { get; set; }
        public string Spouse { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Occupation { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<int> NoOfChildrens { get; set; }
        public Nullable<int> VisitNumber { get; set; }
        public Nullable<int> AgeID { get; set; }
        public string email { get; set; }
    }
}
