//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PomeDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        public int ID { get; set; }
        public string Qeustion { get; set; }
        public Nullable<bool> IsLinkedQuestion { get; set; }
        public string ControlType { get; set; }
        public Nullable<int> OrderList { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> LinkedQuestionID { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<int> ReportingFieldID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string System { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
